# Generated by Django 3.0.4 on 2021-04-28 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('zipcode', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('fainting', models.BooleanField(default=False)),
                ('bruise', models.BooleanField(default=False)),
                ('vein', models.BooleanField(default=False)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('total', models.BooleanField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'blood_donor',
            },
        ),
    ]
