# Generated by Django 3.2 on 2021-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
