# Generated by Django 3.0.4 on 2021-04-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_auto_20210428_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='none',
        ),
    ]
